FROM pypy:2

RUN apt update -yqq && \
    apt install -yqq --no-install-recommends \
        ca-certificates \
        gcc \
        libc-dev \
        libssl-dev \
        unzip \
        python3-dev \
        python3-uno \
        libreoffice-calc \
        wget && \
    wget https://bootstrap.pypa.io/get-pip.py -O - | python3 && \
    pypy -m pip install -U pip && \
    python3 -m pip install psutil unotools

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

RUN wget https://github.com/decalage2/ViperMonkey/archive/master.zip && \
    unzip master.zip && \
    cd ViperMonkey-master && \
    pypy -m pip install -U -r requirements.txt

WORKDIR /malware
ENTRYPOINT [ "pypy", "/home/appuser/ViperMonkey-master/vipermonkey/vmonkey.py" ]
CMD [ "-h" ]
